name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.1
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.4
      with:
       node-version: 20.x
    - name: run
      run: npm i
